server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=UTC&noDatetimeStringSync=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver
  thmeleaf:
    check-templates:  true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    cache:  false

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package:  com.gh.Demo.module