server:
  port: 8080
  session:
    timeout: 300
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/admin?serverTimezone=UTC&noDatetimeStringSync=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver
  thmeleaf:
    check-templates:  true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    cache:  false

mybatis:
  mapper-locations: classpath:mapper/*Mapper/*.xml
  type-aliases-package:  com.gh.Demo.module
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
